name: Build AMI with Packer

on: [push]

jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Packer
      uses: hashicorp/setup-packer@v1
      with:
        packer-version: '1.10.0'
    - name: Build AMI
      run: packer build template.json
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

